# Generated by Django 4.1.7 on 2023-03-22 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='detail',
            new_name='details',
        ),
    ]
