# Generated by Django 4.1.7 on 2023-03-27 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0005_farmerrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='farmerRequest',
        ),
    ]
