# Generated by Django 4.1.7 on 2023-03-28 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0007_farmerrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='farmerRequest',
        ),
    ]
