# Generated by Django 4.1.7 on 2023-03-28 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0018_market'),
        ('Farmer', '0010_delete_farmerrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='farmerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('status', models.IntegerField(default=0)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.farmer')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.market')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Farmer.product')),
            ],
        ),
    ]
