# Generated by Django 4.1.7 on 2023-03-30 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0013_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='farmer',
        ),
    ]
