# Generated by Django 4.1.7 on 2023-03-30 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0018_market'),
        ('Farmer', '0014_remove_product_farmer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='farmer',
        ),
        migrations.AddField(
            model_name='product',
            name='farmer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.farmer'),
        ),
    ]
