# Generated by Django 4.2 on 2023-04-18 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0020_rename_admin_email_admin_email_and_more'),
        ('Farmer', '0016_rename_product_farmerproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerproducts',
            name='ptype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Farmer.producttype'),
        ),
        migrations.AlterField(
            model_name='farmerrequest',
            name='farmer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.farmer'),
        ),
        migrations.AlterField(
            model_name='farmerrequest',
            name='market',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.market'),
        ),
        migrations.AlterField(
            model_name='farmerrequest',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Farmer.farmerproducts'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Farmer.farmerproducts'),
        ),
    ]
