# Generated by Django 4.2 on 2023-04-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0019_auctionslotbooking_slotreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionslotbooking',
            name='slot_status',
            field=models.IntegerField(default=0),
        ),
    ]
