# Generated by Django 4.2 on 2023-04-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0021_alter_auctionslotbooking_slotbookdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='req_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
