# Generated by Django 4.1.7 on 2023-03-04 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
