# Generated by Django 4.1.7 on 2023-03-09 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_subadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subadmin',
        ),
    ]
