# Generated by Django 4.1.7 on 2023-03-13 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_subadmin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='ProductType',
        ),
        migrations.RenameField(
            model_name='producttype',
            old_name='name',
            new_name='product_type',
        ),
        migrations.DeleteModel(
            name='Sub',
        ),
    ]
