# Generated by Django 4.1.7 on 2023-03-20 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_rename_category_producttype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('photo', models.FileField(upload_to='UserPhoto/')),
                ('rate', models.CharField(max_length=50)),
                ('ptype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.producttype')),
                ('subadmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.subadmin')),
            ],
        ),
    ]
