# Generated by Django 4.1.7 on 2023-03-22 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
    ]
