# Generated by Django 4.1.7 on 2023-03-29 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
