# Generated by Django 4.1.7 on 2023-03-29 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0018_market'),
        ('Admin', '0022_farmerfeedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='marketFeedback',
            new_name='Feedback',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='market',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='user',
        ),
        migrations.DeleteModel(
            name='farmerFeedback',
        ),
        migrations.DeleteModel(
            name='UserFeedback',
        ),
    ]
