# Generated by Django 4.1.7 on 2023-03-29 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0024_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='market',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
