# Generated by Django 4.1.7 on 2023-03-29 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0026_feedback_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
