# Generated by Django 4.1.7 on 2023-03-29 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0018_market'),
        ('Admin', '0027_delete_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=6000)),
                ('status', models.IntegerField(default=0)),
                ('reply', models.CharField(default='Not Yet Viewed', max_length=5000)),
                ('date', models.DateField(auto_now_add=True)),
                ('farmer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.farmer')),
                ('market', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.market')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.user')),
            ],
        ),
    ]
