# Generated by Django 4.2 on 2023-04-17 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0032_producttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subadmin',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.district'),
        ),
    ]
