# Generated by Django 4.2 on 2023-04-18 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subadmin', '0003_alter_productgallery_product_and_more'),
        ('Admin', '0034_alter_subadmin_district'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductType',
            new_name='SProductType',
        ),
    ]
