# Generated by Django 4.2 on 2023-04-20 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0021_alter_farmer_place_alter_market_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketevent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketevent_date', models.DateField()),
                ('marketevent_starttime', models.TimeField()),
                ('marketevent_description', models.TextField(null=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.market')),
            ],
        ),
    ]
