# Generated by Django 4.2 on 2023-04-14 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0032_producttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.TextField(null=True)),
                ('product_image', models.FileField(upload_to='productimg/')),
                ('product_rate', models.CharField(max_length=100)),
                ('product_date', models.DateField(auto_now=True)),
                ('producttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.producttype')),
                ('subadmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.subadmin')),
            ],
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_stock', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subadmin.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productgallery_image', models.FileField(upload_to='productimg/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subadmin.product')),
            ],
        ),
    ]
