# Generated by Django 4.2 on 2023-04-18 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0034_alter_subadmin_district'),
        ('Subadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
