# Generated by Django 4.1.7 on 2023-03-10 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_farmer_market_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Farmer',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Market',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
