# Generated by Django 4.1.7 on 2023-03-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='logo',
            field=models.FileField(upload_to='Marketlogo'),
        ),
        migrations.AlterField(
            model_name='market',
            name='proof',
            field=models.FileField(upload_to='Marketproof'),
        ),
    ]
