# Generated by Django 4.1.7 on 2023-03-10 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0011_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='district',
        ),
    ]
