# Generated by Django 4.1.7 on 2023-03-11 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0012_remove_farmer_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='place',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.RemoveField(
            model_name='market',
            name='place',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Farmer',
        ),
        migrations.DeleteModel(
            name='Market',
        ),
    ]
