# Generated by Django 4.1.7 on 2023-03-11 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0014_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='district',
        ),
    ]
