# Generated by Django 4.1.7 on 2023-03-21 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0016_subadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Market',
        ),
    ]
