# Generated by Django 4.2 on 2023-04-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0018_market'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=100, null=True)),
                ('admin_email', models.CharField(max_length=100)),
                ('admin_password', models.CharField(max_length=50)),
            ],
        ),
    ]
