# Generated by Django 4.2 on 2023-04-17 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0019_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='admin_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='admin_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='admin_password',
            new_name='password',
        ),
    ]
