# Generated by Django 4.2 on 2023-04-26 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0022_alter_farmer_email_alter_farmer_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subadmin',
        ),
    ]
