# Generated by Django 4.1.7 on 2023-03-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_rename_userrequest_sendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendrequest',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
