# Generated by Django 4.1.7 on 2023-03-29 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_userfeedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userfeedback',
        ),
    ]
