# Generated by Django 4.2 on 2023-04-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendrequest',
            name='payment_sts',
            field=models.IntegerField(default=0),
        ),
    ]
