# Generated by Django 4.2 on 2023-04-18 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0017_alter_farmerproducts_ptype_and_more'),
        ('Guest', '0021_alter_farmer_place_alter_market_place_and_more'),
        ('User', '0016_sendrequest_payment_sts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendrequest',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Farmer.farmerproducts'),
        ),
        migrations.AlterField(
            model_name='sendrequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.user'),
        ),
    ]
