# Generated by Django 4.2 on 2023-04-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0017_alter_sendrequest_product_alter_sendrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendrequest',
            name='req_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
